---
sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
before_install: gem update --remote bundler
install:
  - bundle install --retry 3
script: ./test/run_tests.sh
