---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- jruby
- ruby-head
script: rake travis
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
