---
<<<<<<< HEAD
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
sudo: false
cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
language: ruby
notifications:
  email:
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- jruby-9.2.5.0
- ruby-head
script: rake travis
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
